spring:
  application:
    name: "notificationservice"
  config:
    import: "optional:configserver:http://localhost:8071/"

  datasource:
    url: jdbc:postgresql://localhost:5432/userservicedb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  mail:
    host: smtp.gmail.com
    port: 587
    username: 220107072@stu.sdu.edu.kz
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

server:
  port: 8083

event:
  topic:
    verification: account-verification
    password-reset: password-reset

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    enabled: true
  api-docs:
    path: /v3/api-docs