spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userservicedb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 9085

event:
  topic:
    listing:
      availability:
        request: "listing-availability-request"
        response: "listing-availability-response"
        block: "listing-availability-block"
        unblock: "listing-availability-unblock"
    payment: payment-topic

listing-service:
  url: http://localhost:8082/api/v1/listings
