server:
  port: 8082

spring:
  application:
    name: "listingservice"
  config:
    import: "optional:configserver:http://localhost:8071/"
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: listing-service

jwt:
  secret-key: ${JWT_SECRET_KEY:ZGlnNF4lXiYqKCo0MjRnZXdnZXdma2Vmfmg4gr25fbg15}
  signature-algorithm: HS256

minio:
  bucket: "images"
  url: "http://localhost:9000/"
  accessKey: "minioadmin"
  secretKey: "minioadmin"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

event:
  topic:
    listing:
      created: "listing-created"
      updated: "listing-updated"
      availability:
        request: "listing-availability-request"
        response: "listing-availability-response"
        block: "listing-availability-block"
        unblock: "listing-availability-unblock"