services:
    userservicedb:
        container_name: userservicedb
        image: postgres:15
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "postgres" ]
            timeout: 10s
            retries: 10
            interval: 10s
            start_period: 10s
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: userservicedb
        ports:
            - 5432:5432
        networks:
            - rentspace
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        restart: always
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_CONFIG_SERVER_MODE: "True"
            PGADMIN_LOG_LEVEL: "DEBUG"
        depends_on:
            userservicedb:
                condition: service_healthy
        volumes:
            - ./postgres_db_data/servers.json:/pgadmin4/servers.json
            - ./postgres_db_data/pgpass:/pgpass
        user: root
        entrypoint: /bin/sh -c "chmod 600 /pgpass && /entrypoint.sh"
        networks:
            - rentspace
#        extends:
#            file: common-config.yml
#            service: base-service

    minio:
        container_name: minio
        image: minio/minio:latest
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - minio_data:/data
        command: server /data --console-address ":9001"
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        networks:
            - rentspace

    configservice:
        container_name: configservice
        image: d0niiel/configservice:v1
        ports:
            - "8071:8071"
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:8071/actuator/health/readiness || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 10
        networks:
            - rentspace

    discoveryservice:
        container_name: discoveryservice
        image: d0niiel/discoveryservice:v1
        ports:
            - "8761:8761"
        restart: always
        environment:
            SPRING_PROFILES_ACTIVE: prod
            SPRING_CONFIG_IMPORT: "configserver:http://configservice:8071/"
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health/readiness || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 10
        depends_on:
            configservice:
                condition: service_healthy
        networks:
            - rentspace

    userservice:
        image: d0niiel/userservice:v1
        container_name: userservice
        restart: always
#        extends:
#            file: common-config.yml
#            service: app-service
        ports:
            - "8080:8080"
        depends_on:
            discoveryservice:
                condition: service_healthy
            userservicedb:
                condition: service_healthy
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://userservicedb:5432/userservicedb
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres
            SPRING_PROFILES_ACTIVE: prod
            SPRING_CONFIG_IMPORT: "configserver:http://configservice:8071/"
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discoveryservice:8761/eureka/"
        networks:
            - rentspace

volumes:
    minio_data:

networks:
    rentspace:
        driver: bridge
