spring:
  application:
    name: search-service
  config: "optional:configserver:http://localhost:8071/"
  kafka:
    bootstrap-servers: localhost:9092
  elasticsearch:
    uris: http://localhost:9200
server:
  port:8085
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true