server:
  port: 8080

spring:
  application:
        name: "userservice"
  config:
    import: "optional:configserver:http://localhost:8071/"

  kafka:
    bootstrap-servers: localhost:9091, localhost:9092, localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
        max-in-flight-requests-per-connection: 5
        linger-ms: 0
        request-timeout-ms: 30000
        delivery.timeout.ms: 120000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

jwt:
  secret-key: "ZGlnNF4lXiYqKCo0MjRnZXdnZXdma2Vmfmg4gr25fbg15"
  access-expiration-time: 3600000
  refresh-expiration-time: 604800000

app:
  confirm-account-url: http://localhost:8080/api/v1/auth/confirm?token=

event:
  topic:
    verification: account-verification
    password-reset: password-reset

logging:
  level:
    com.rentspace.userservice: DEBUG
    org.springframework.security: DEBUG